---
platform: linux

image_resource:
    type: docker-image
    source: { repository: busybox }

inputs:
 - name: pass-output

outputs:
 - name: get-some-files

run:
 path: sh
 args: [pass-output/ci/tasks/create-file.sh]