---
platform: linux

image_resource:
    type: docker-image
    source: { repository: busybox }

inputs:
 - name: create-some-files

outputs:
 -name: get-some-files

run:
 path: sh
 args: [create-some-files/ci/tasks/create-file.sh]