---
platform: linux
image_resource:
    type: docker-image
    source: { repository: node, tag: slim}

inputs:
 - name: pass-output
 - name: get-some-files

run: 
 path: sh
 args: [pass-output/ci/tasks/get-file.sh]