---
platform: linux
image_resource:
    type: docker-image
    source: { repository: node, tag: slim}

inputs:
 #- name: create-some-files
 - name: get-some-files

run: 
 path: sh
 args: [create-some-files/ci/tasks/get-file.sh]