resources:
- name: pass-output
  type: git
  source:
    uri: https://github.com/UmamaheshMaxwell/task-outputs-inputs.git
    branch: master

jobs:
 - name: job-create-files
   public: true
   plan:
    - get: pass-output
    
    - task: create-files
      config:
        platform: linux

        image_resource:
            type: docker-image
            source: { repository: busybox }

        inputs:
        - name: pass-output
          path: pass-output

        outputs:
        - name: get-some-files

        run:
         path: sh
         args: [pass-output/ci/tasks/create-file.sh]
     
    - task: get-files
      file: pass-output/ci/tasks/get-file.yml